app = "websshabi"
primary_region = "phx"

[env]
Server = ""
Spot = ""
idu = ""
secret = ""

[http_service]
force_https = true
internal_port = 5032
min_machines_running = 0
processes = [ "app" ]

[[mounts]]
destination = "/code/nezha"
source = "websshabi_data"

[[vm]]
size = "shared-cpu-1x"
